### PR TITLE
Add optional argument to gemdash, to specify trajectory location

### PR DESCRIPTION
**Pull request by v1kko**
This pull request adds the optional `--file [FILE]` argument to `gemdash`

### CODE REVIEW

**Comment by v1kko** [comment]
Hi @AstyLavrinenko can you test this branch on Windows to check if it works?

**Comment by AstyLavrinenko** [comment]
> Hi @AstyLavrinenko can you test this branch on Windows to check if it works?

Hi Victor, I checked. I can open the dashboard without specifying the path to the vasprun file. However, when the dashboard is open, I cannot select or change the file path. Inserting the path directly doesn't work either. Also It seems I need to open a new dashboard if I want to switch to a different vasprun file since changing the path in the open window failed.

**Comment by v1kko** [comment]
I am not able to reproduce such an issue. The only time I cannot adjust the path is when I stop gemdash on the commandline, then the boxes in the dashboard get grayed out. However if I restart gemdash again (even with a different `--file <vasprun.xml path>`) it becomes selectable again. (provided that it servers the dashboard on the same location, `http://localhost:8501` for example.)

Can you share a step by step example of how you use it when you encounter the issue?
Something like:
- Start `gemdash -f simulation1/vasprun.xml`, running on `http://localhost:8501`
- Open browser at `http://localhost:8501`
- Stop gemdash
- Start `gemdash -f simulation2/vasprun.xml`, running on `http://localhost:8501`
- Issue while changing path in first browser!

**Comment by v1kko** [comment]
I am merging this now, if there are still issues, we can take care of them via a new issue/pull request

**Comment by AstyLavrinenko** [comment]
Hi @v1kko 
Sorry for the late reply—it's been a bit of a crazy few weeks on my end. I just checked the dashboard installed locally from a new repo. It worked, I can paste the path or change it directly in the browser

**Pull request merged**
